### ISSUE TITLE
Could you please add description of the data curated in test_data?

### ISSUE THREAD

**Issue by thejustpark** [aicb-ZhangLabs/Venus#3]
Dear Venus Team, 

Thank you for providing the code and data for us to test Venus. 
Could you please explain what is the data you have in the test_data folder? 
I mean, I am wondering about the biological context of bulk_1.fastq.gz, bulk_2.fastq.gz, singlecell_1cDNA.fastq.gz, and singlecell_2CB+UMI.fastq.gz. 

Thanks, 
HJ

**Comment by Cheyujlee** [comment]
Dear HJ,
Thank you for your interest.

The bulk and single-cell test data came from HIV-infected T-cells and monocytes, respectively, accession number PRJNA448285 [link](https://doi.org/10.1126/scitranslmed.aaz0802) and PRJNA644611 [link](https://doi.org/10.1128/mBio.01037-20). 
They were from the same data analyzed in the results sections (Fig. 4, 6), except that the test data were down-sampled so that the file sizes were less than 100 MB, as required by GitHub. 
Reference sequences for both human and viruses were downloaded from NCBI’s RefSeq database.

I have also added a README.md prompted by your suggestion.

Let me know if you have any additional Qs.

Best,
Che Yu.

**Comment by Cheyujlee** [comment]
Hi HJ,
I am going to close this issue for now. Feel free to re-open this issue if you still have any Qs.

Thanks,
Che Yu.
