### ISSUE TITLE
Integration sites from single-cell data

### ISSUE THREAD

**Issue by pfren1998** [aicb-ZhangLabs/Venus#4]
Hi:
   Recently I am using Venus to find the integration sites with single-cell rna-seq data, however, I only got the fusion sites containing human genes, have you tried to indentify the integration sites with single-cell rna-seq data in your paper? Thanks!
    Best wishes

**Comment by Cheyujlee** [comment]
Hi @pfren1998 ,
Thank you for your interest in the software. Can you clarify by fusion sites containing human genes? Did you want to detect the viral genes that were inserted into the human genome?

So, we have tried identifying the integration sites with scRNA-seq but we couldn't find any because they were just not as deeply sequenced as the bulk RNA-seq data we later analyzed.

Best,
Che Yu "Joey".

**Comment by pfren1998** [comment]
Thanks for your quick reply!
