### ISSUE TITLE
conda install error 

### ISSUE THREAD

**Issue by antoine4ucsd** [aicb-ZhangLabs/Venus#5]
hello 
I am very interested in evaluating Venus for my data (scRNAseq data from persons with HIV)
I am trying to set up the venus conda env but I get the an error when running
```
conda create --name venus --file ${repo_dir}/reference_files/venus_spec-file.txt
```
the log is attached.
would you have any suggestions?

thank you in advance for your help!

[venus_conda_install.txt](https://github.com/aicb-ZhangLabs/Venus/files/11786446/venus_conda_install.txt)

**Comment by antoine4ucsd** [comment]
looks like the spec-file is linux specific. do you have an udapted one for mac os?
thank you!

**Comment by Cheyujlee** [comment]
Hi @antoine4ucsd ,
Thank you for your interest. Currently building one.
Thanks!
Che Yu.

**Comment by antoine4ucsd** [comment]
that would be great
thank you!

**Comment by Cheyujlee** [comment]
Hi @antoine4ucsd 

Sorry for the delay! Idk if you are working on an ARM64 apple silicon mac, but for me (working on an M1), the problem is that conda doesn't have a lot of Venus's depedencies available for apple silicon just yet.
![image](https://github.com/aicb-ZhangLabs/Venus/assets/70779123/39dfbb8c-e1dc-4876-b2e7-99c03ce4d9af)


Here is the Conda env file for the list of python packages that could be found on Conda:
* attached: [venus_macOS-spec_file.txt](https://github.com/aicb-ZhangLabs/Venus/files/11950155/venus_macOS-spec_file.txt) `conda create --name <env> --file <this file>`

However, the most important packages you need to manually install and add to $Path:
* STAR Aligner (under-the-hood read mapping software): [link](https://github.com/alexdobin/STAR#compiling-from-source)
* Install [Homebrew](https://brew.sh/) to install [Samtools](https://formulae.brew.sh/formula/samtools)
* Install [Trim Galore](https://github.com/FelixKrueger/TrimGalore#installation)

**_Last but not least, most importantly, I am going to assume you have at least 30 GB (prob more to be safe) of RAM on your Mac. The reason why STAR Aligner is fast is that it utilizes a lot of memory. The human genome will require 30 GB of RAM. If not, it will take forever to map. For me, my lap top only has 16 GB of RAM._**

Sorry again for the 2-wk delay. Hope this helps! Feel free to reply back for any further Q's.

Have a good holiday!
CheYu "Joey".

**Comment by antoine4ucsd** [comment]
thank you. I am also working on a last gen macbook pro. I will give it a try asap
Best,
